### PR TITLE
sir, i have added ai option

### PR DESCRIPTION
**Pull request by anupam66**

### CODE REVIEW

**Review by anupamkush9 — COMMENTED** [review]
can you give me more detail and optimize it.

**Comment by anupam66** [comment]
> can you give me more detail and optimizdfskljdsflkjsdlk;jasfdl;jfsdakl;sdf

**Comment by anupam66** [comment]
sir i have added more detail

**Comment by anupam66** [comment]
> can you give me more detail and optimize it.

ok su\

**Pull request merged**
